### ISSUE TITLE
powershell has stopped working on x86

### ISSUE THREAD

**Issue by xp3ctus** [khr0x40sh/MacroShop#3]
powershell has stopped working on x86, it works on x64

**Comment by khr0x40sh** [comment]
What version of windows/Office are you using?

**Comment by xp3ctus** [comment]
windows 7 office 2013, it always runs on x64 but on x86 it just ran the first time only and then started giving that error

**Comment by khr0x40sh** [comment]
I'll look into it.  Anyway you can share the actual error message with me?

**Comment by khr0x40sh** [comment]
This is not an issue with MacroShop, but between the MSF handler and the payload generated by Veil.  Occasionally, it appears the handler will lock up and not receive new callbacks.  This may be due to ExitOnSession not being set to False, a payload/handler architecture mismatch (x86/x64), the handler has expired, or MSF needs a restart.  This item will be closed.
